baseURL = "https://italianairogroup.github.io/AIROwebsite/"
languageCode = "en-us"
title = "AIRO"
theme = 'mainroad'
relativeURLs = true


[Params.logo]
 image = "img/robot_example_scaled.jpg" # Logo image. Path relative to "static"
 title = "Italian Artificial Intelligence and Robotics Group (AIRO)" # Logo title, otherwise will use site title
  
[Params.style.vars]
     highlightColor = "#5588ff"

[Params]
  customJS = ["https://code.jquery.com/jquery-3.7.1.min.js"]


[menu]
# HOME
  [[menu.main]]
    identifier = "home"
    name = "About"
    url="/home"
    weight = 1000
# MEMBERS
  [[menu.main]]
    identifier = "members"
    name = "Members"
    url="/members"
    weight = 2000
# RESEARCH GROUPS
  [[menu.main]]
    identifier = "reasearch_groups"
    name = "Research Groups"
    url="/research_groups"
    weight = 2000
# WORKSHOPS
  [[menu.main]]
    identifier = "workshops"
    name = "WORKSHOPS"
#    url="/workshop"
    weight = 2000
# AIRO 2022
  [[menu.main]]
    identifier = "AIRO2022"
    name = "AIRO2022"
    parent = "workshops"
    weight = 2000
# AIRO 2023
  [[menu.main]]
    identifier = "AIRO2023"
    name = "AIRO2023"
    parent = "workshops"
    weight = 2000
    
    
    
    
# AIRO 2022
  [[menu.main]]
    identifier = "AIRO2022_home"
    name = "HOME"
    parent = "AIRO2022"
    weight = 2000
    url="/workshop/AIRO2022/home"
# AIRO 2022
  [[menu.main]]
    identifier = "AIRO2022_dates"
    name = "DATES"
    parent = "AIRO2022"
    weight = 2000
    url="/workshop/AIRO2022/dates"

